# Generated by Django 5.2.3 on 2025-07-04 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0002_submission_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='language',
            field=models.CharField(choices=[('python', 'Python'), ('cpp', 'C++')], default='python', max_length=10),
        ),
    ]
