# Generated by Django 5.2.3 on 2025-07-13 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0003_submission_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('start_time', models.DateTimeField()),
                ('duration_minutes', models.IntegerField(default=90)),
                ('problems', models.ManyToManyField(related_name='contests', to='judge.problem')),
            ],
        ),
    ]
