# Generated by Django 5.2.4 on 2025-08-01 08:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIAssistantLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField()),
                ('response', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('tokens_used', models.IntegerField(default=0)),
                ('model_used', models.CharField(default='gpt-3.5-turbo', max_length=50)),
                ('response_time', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ai_assistant_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
